# Generated by Django 5.1.4 on 2025-01-21 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_user_last_name'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='role',
            table='roles_name_list',
        ),
    ]
