# Generated by Django 5.1.4 on 2025-01-21 11:00

import authentication.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_role_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.ForeignKey(default=authentication.models.get_default_role, on_delete=django.db.models.deletion.PROTECT, to='authentication.role'),
        ),
    ]
