# Generated by Django 5.1.4 on 2025-01-29 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pending_email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='pending_mobile',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
