# Generated by Django 4.2.20 on 2025-03-12 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_user_pending_email_user_pending_mobile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='pending_email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='pending_mobile',
        ),
    ]
